#controller_list:
#  - name: quadrotor_controller
#    action_ns: follow_joint_trajectory
#    type: FollowJointTrajectory
#    default: true
#    joints:
#     - virtual_joint
controller_list:
  - name: multi_dof_joint_trajectory_action
    type: MultiDofFollowJointTrajectory
    default: true
    joints:
      - virtual_joint
