sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /camera/depth/points
    max_range: 6.0
    point_subsample: 1
    padding_offset: 0.1
    padding_scale: 1.0
